services:

  Backend:
    build: ./Backend
    container_name: Spa-website-Backend
    ports:
      - "5001:5001"
    environment:
      - name=value
    networks:
      - Spa-networks
    volumes:
      - 
  Frontend:
    build: ./Frontend
    container_name: Spa-website-Frontend
    ports:
    - 5173:5173
    environment:
      - name=value
    networks:
      - Spa-networks
    volumes:
      -

volumes:

networks:

